# Generated by Django 4.1.4 on 2023-06-23 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancestatus",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="attendence",
            name="students",
            field=models.ManyToManyField(
                through="Groups.AttendanceStatus", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
