# Generated by Django 4.1.4 on 2023-06-24 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Student", "0001_initial"),
        ("Groups", "0002_alter_attendancestatus_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancestatus",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Student.student"
            ),
        ),
        migrations.AlterField(
            model_name="attendence",
            name="students",
            field=models.ManyToManyField(
                through="Groups.AttendanceStatus", to="Student.student"
            ),
        ),
    ]
